# Generated by Django 5.2.7 on 2025-10-19 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_category_workout_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='category',
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Arms', 'Arms'), ('Shoulders', 'Shoulders'), ('Core', 'Core')], max_length=50)),
                ('sets', models.PositiveBigIntegerField(default=3)),
                ('reps', models.PositiveBigIntegerField(default=10)),
                ('weight', models.FloatField(default=0, help_text='Lb')),
                ('notes', models.TextField(blank=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excercises', to='workouts.workout')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
