# Generated by Django 5.2.7 on 2025-10-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_musclepart_delete_musclegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_parts',
            field=models.ManyToManyField(related_name='exercises', to='workouts.musclepart'),
        ),
    ]
